name: lambda-calculus
version: 0.1.0.0
github: "ksrky/lambda-calculus"
license: BSD3
author: "ksrk"
maintainer: "example@example.com"
copyright: "2022 ksrk"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ksrky/lambda-calculus#readme>

dependencies:
  - base >= 4.7 && < 5
  - array
  - directory
  - haskeline
  - hspec
  - megaparsec
  - mtl
  - parser-combinators
  - safe-exceptions
  - text

library:
  source-dirs: src

executables:
  typed:
    main: Main.hs
    source-dirs: src/typed
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculus
  ex-typed:
    main: Main.hs
    source-dirs: src/ex-typed
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculus
  rectype:
    main: Main.hs
    source-dirs: src/rectype
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculus
  recon:
    main: Main.hs
    source-dirs: src/recon
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lambda-calculus
